theme: jekyll-theme-minimal
title: Ayesha Bhimdiwala
title: Ayesha Bhimdiwala
name: Ayesha Bhimdiwala
description: Graduate Student, Learning and Data Science
avatar: https://aysh20.github.io/images/bestpic2018.jpg
url: "https://aysh20.github.io"
font: Papyrus, fantasy

